# -*- coding: utf-8 -*-
"""backend.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wtrZdgOZBMzulwie64uskVzDzLZh3hjM
"""

import os
import glob
import time
import threading
import subprocess
import ast
import joblib
import numpy as np
import pandas as pd

from flask import Flask, request, jsonify
from flask_cors import CORS

app = Flask(__name__)
CORS(app)

DATA_FOLDER = r"C:\Users\M S I\OneDrive\Documents\GitHub\Research-Project\data"
PSYCHOPY_PATH = r"C:\Users\M S I\OneDrive\Documents\GitHub\Research-Project\Cheese.psyexp"
PSYCHOPY_EXE = r"C:\Program Files\PsychoPy\python.exe"
TRAIN_FILE = os.path.join(DATA_FOLDER, "training_dataset.csv")
MODEL_FILE = os.path.join(DATA_FOLDER, "reason_prediction_model.pkl")

participant_jobs = {}

def parse_list_cell(value):
    if pd.isna(value):
        return []
    if isinstance(value, list):
        return value
    if isinstance(value, (int, float)):
        return [value]
    value = str(value).strip()
    if value == "" or value.lower() == "nan":
        return []
    try:
        parsed = ast.literal_eval(value)
        if isinstance(parsed, list):
            return parsed
        return [parsed]
    except Exception:
        return [value]

def get_last_numeric(value):
    arr = parse_list_cell(value)
    nums = []
    for v in arr:
        try:
            nums.append(float(v))
        except Exception:
            pass
    return nums[-1] if nums else np.nan

def get_last_string(value):
    arr = parse_list_cell(value)
    if not arr:
        return None
    return str(arr[-1]).strip()

def standardize_reason_labels(series):
    return (
        series.astype(str)
        .str.strip()
        .str.lower()
        .replace({
            "price": "Price",
            "brand": "Brand",
            "familiarity": "Familiarity"
        })
    )

def train_model_if_needed():
    if os.path.exists(MODEL_FILE):
        return

    from sklearn.model_selection import train_test_split
    from sklearn.compose import ColumnTransformer
    from sklearn.pipeline import Pipeline
    from sklearn.impute import SimpleImputer
    from sklearn.preprocessing import OneHotEncoder, StandardScaler
    from sklearn.ensemble import RandomForestClassifier

    df = pd.read_csv(TRAIN_FILE)
    df["reason"] = standardize_reason_labels(df["reason"])
    df["gender"] = df["gender"].astype(str).str.strip().str.title()

    X = df[["brochure_id", "age", "gender", "reaction_time", "gaze_x", "gaze_y"]]
    y = df["reason"]

    X_train, _, y_train, _ = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    numeric_features = ["brochure_id", "age", "reaction_time", "gaze_x", "gaze_y"]
    categorical_features = ["gender"]

    preprocessor = ColumnTransformer([
        ("num", Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler())
        ]), numeric_features),
        ("cat", Pipeline([
            ("imputer", SimpleImputer(strategy="most_frequent")),
            ("onehot", OneHotEncoder(handle_unknown="ignore"))
        ]), categorical_features)
    ])

    model = Pipeline([
        ("preprocessor", preprocessor),
        ("classifier", RandomForestClassifier(
            n_estimators=300,
            max_depth=8,
            random_state=42,
            class_weight="balanced"
        ))
    ])

    model.fit(X_train, y_train)
    joblib.dump(model, MODEL_FILE)

def get_latest_csv(after_time=None):
    csv_files = glob.glob(os.path.join(DATA_FOLDER, "*.csv"))
    valid = []

    for file in csv_files:
        name = os.path.basename(file).lower()
        if "training" in name or "prediction" in name or "converted" in name:
            continue
        if after_time and os.path.getmtime(file) <= after_time:
            continue
        valid.append(file)

    if not valid:
        return None

    return max(valid, key=os.path.getmtime)

def convert_psychopy_to_rows(psychopy_file, participant_id, age, gender):
    raw_df = pd.read_csv(psychopy_file)

    brochure_blocks = {
        1: "mous_1",
        2: "mouse_2",
        3: "mouse_3",
        4: "mouse_4",
        5: "mouse_5"
    }

    rows = []

    for brochure_id, prefix in brochure_blocks.items():
        x_col = f"{prefix}.x"
        y_col = f"{prefix}.y"
        t_col = f"{prefix}.time"
        c_col = f"{prefix}.clicked_name"

        if c_col not in raw_df.columns:
            continue

        valid_rows = raw_df[raw_df[c_col].notna()]
        if valid_rows.empty:
            continue

        selected = valid_rows.iloc[0]

        rows.append({
            "participant": participant_id,
            "brochure_id": brochure_id,
            "age": int(age),
            "gender": str(gender).title(),
            "reaction_time": get_last_numeric(selected[t_col]) if t_col in raw_df.columns else np.nan,
            "gaze_x": get_last_numeric(selected[x_col]) if x_col in raw_df.columns else np.nan,
            "gaze_y": get_last_numeric(selected[y_col]) if y_col in raw_df.columns else np.nan,
            "clicked_item": get_last_string(selected[c_col]),
        })

    return pd.DataFrame(rows)

def predict_rows(df):
    model = joblib.load(MODEL_FILE)

    X = df[["brochure_id", "age", "gender", "reaction_time", "gaze_x", "gaze_y"]]
    probs = model.predict_proba(X)
    preds = model.predict(X)
    class_names = model.named_steps["classifier"].classes_

    prob_df = pd.DataFrame(
        probs * 100,
        columns=[f"{cls}_Percentage" for cls in class_names]
    )

    final_df = df.copy()
    final_df["Predicted_Reason"] = preds

    for col in prob_df.columns:
        final_df[col] = prob_df[col].round(2)

    return final_df

def background_task(participant_id, age, gender):
    participant_jobs[participant_id] = {"status": "running", "results": None, "error": None}

    try:
        train_model_if_needed()

        before_time = time.time()

        subprocess.Popen([PSYCHOPY_EXE, PSYCHOPY_PATH], shell=False)

        latest_csv = None
        start = time.time()
        while time.time() - start < 600:
            latest_csv = get_latest_csv(after_time=before_time)
            if latest_csv:
                break
            time.sleep(2)

        if not latest_csv:
            raise Exception("No new PsychoPy CSV found.")

        tidy_df = convert_psychopy_to_rows(latest_csv, participant_id, age, gender)
        result_df = predict_rows(tidy_df)

        results = result_df[[
            "brochure_id",
            "clicked_item",
            "Brand_Percentage",
            "Familiarity_Percentage",
            "Price_Percentage",
            "Predicted_Reason"
        ]].to_dict(orient="records")

        participant_jobs[participant_id] = {
            "status": "completed",
            "results": results,
            "error": None
        }

    except Exception as e:
        participant_jobs[participant_id] = {
            "status": "error",
            "results": None,
            "error": str(e)
        }

@app.route("/api/launch-psychopy", methods=["POST"])
def launch_psychopy():
    data = request.get_json()

    participant_id = data.get("id")
    age = data.get("age")
    gender = data.get("gender")

    if not participant_id or not age or not gender:
        return jsonify({"error": "id, age, and gender are required"}), 400

    thread = threading.Thread(
        target=background_task,
        args=(participant_id, age, gender),
        daemon=True
    )
    thread.start()

    return jsonify({"status": "started"})

@app.route("/api/latest-results", methods=["GET"])
def latest_results():
    participant_id = request.args.get("participantId")

    if not participant_id:
        return jsonify({"error": "participantId is required"}), 400

    job = participant_jobs.get(participant_id)
    if not job:
        return jsonify({"status": "not_found"}), 404

    return jsonify(job)

if __name__ == "__main__":
    train_model_if_needed()
    app.run(host="0.0.0.0", port=5000, debug=True)

